cache_path: .licenses

apps:
  - name: arduino-app-bricks
    source_path: .
    sources:
      pip: true
    python:
      virtual_env_dir: "/venvs/arduino-app-bricks"

  - name: python-base
    source_path: .
    sources:
      pip: true
    python:
      virtual_env_dir: "/venvs/python-base"

  - name: aihub-models-runner
    source_path: .
    sources:
      pip: true
    python:
      virtual_env_dir: "/venvs/aihub-models-runner"

  - name: gesture-recognition-runner
    source_path: .
    sources:
      pip: true
    python:
      virtual_env_dir: "/venvs/gesture-recognition-runner"

stale_records_action: error

ignored:
  pip:
    - pip
    - setuptools
    - wheel
    - uv
    - arduino-app-bricks
    - arduino_app_bricks

allowed:
  - mpl-2.0
  - apache-2.0
  - mit
  - mit-cmu
  - bsd-2-clause
  - bsd-3-clause
  - cc0-1.0
  - isc
  - psf-2.0
  - unlicense
  - ofl-1.1
  - lgpl-3.0-only
  - epl-2.0
  - zpl-2.1
