id: arduino:local_asr
name: Local Automatic Speech Recognition
description: Automatic Speech Recognition brick for offline speech-to-text processing
category: audio
requires_model: true
requires_container: true
# mount_devices_into_container: true
# required_devices:
#   - ?
model: whisper-small
model_configuration_variables:
  - VAD_LEN_HANGOVER
variables:
- name: VAD_LEN_HANGOVER
  description: Length of hangover for Voice Activity Detection (in number of frames of 10ms duration)
  hidden: true
  default_value: 70