id: arduino:visual_anomaly_detection
name: Visual Anomaly Detection
description: |
  Brick for visual anomaly detection using a pre-trained model. It processes images to identify unusual patterns and returns detected anomalies with bounding boxes. 
  Supports pre-trained models provided by the framework or custom anomaly detection models trained on the Edge Impulse platform. 
category: image
requires_container: true
requires_model: true
# For backward compatibility
model: concrete-crack-anomaly-detection
model_by_platform:
    - platform: ventunoq
      model: concreate-crack-anomaly-detection-high-resolution
    - platform: unoq
      model: concrete-crack-anomaly-detection
ai_frameworks_compatibility:
  - edgeimpulse
model_configuration_variables:
  - EI_V_ANOMALY_DETECTION_MODEL
variables:
- name: CUSTOM_MODEL_PATH
  description: Path to the custom model directory
  hidden: true
  default_value: /home/arduino/.arduino-bricks/ei-models
- name: BIND_ADDRESS
  description: Bind address
  hidden: true
  default_value: 127.0.0.1