id: arduino:vlm
name: Visual Language Model (VLM)
description: "Visual Language Model (VLM) Brick enables seamless integration with locally hosted VLMs for advanced AI capabilities in your Arduino projects."
requires_services: ["arduino:genie"]
requires_model: true
model: genie:qwen3-vl-4b
supported_boards: ["ventunoq"]
ai_frameworks_compatibility:
  - genie
