# SPDX-FileCopyrightText: Copyright (C) ARDUINO SRL (http://www.arduino.cc)
#
# SPDX-License-Identifier: MPL-2.0

from langchain_core.language_models import BaseChatModel

from arduino.app_bricks.llm import LargeLanguageModel
from arduino.app_utils import Logger, brick
from arduino.app_internal.core import get_brick_config, get_brick_configured_model

import os
import openai
from typing import Iterator, List, Optional, Any, Callable

logger = Logger("VisionLanguageModel")


@brick
class VisionLanguageModel(LargeLanguageModel):
    """A Brick for interacting with locally-based Vision Language Models (VLMs).

    This class wraps LangChain functionality to provide a simplified, unified interface
    for chatting with models like Qwenm, LLama, Gemma. It supports both synchronous
    'one-shot' responses and streaming output, with optional conversational memory.
    """

    def __init__(
        self,
        api_key: str = os.getenv("LOCAL_LLM_API_KEY", "api_key"),
        system_prompt: str = "",
        temperature: Optional[float] = 0.7,
        max_tokens: int = 256,
        timeout: int = 30,
        tools: List[Callable[..., Any]] = None,
        model: str = None,
        **kwargs,
    ):
        """Initializes the VisionLanguageModel brick with the specified provider and configuration.

        Args:
            api_key (str): The API access key for the target VLM service. Defaults to the
                'LOCAL_LLM_API_KEY' environment variable.
            model (str): The specific model name or identifier to use (e.g., "genie:qwen2.5-3b").
                If not provided, model will be determined from app configuration or default brick configuration.
            system_prompt (str): A system-level instruction that defines the AI's persona
                and constraints (e.g., "You are a helpful assistant"). Defaults to empty.
            temperature (Optional[float]): The sampling temperature between 0.0 and 1.0.
                Higher values make output more random/creative; lower values make it more
                deterministic. Defaults to 0.7.
            max_tokens (int): The maximum number of tokens to generate in the response.
                Defaults to 256.
            timeout (int): The maximum duration in seconds to wait for a response before
                timing out. Defaults to 30.
            tools (List[Callable[..., Any]]): A list of callable tool functions to register. Defaults to None.
            **kwargs: Additional arguments passed to the model constructor

        Raises:
            ValueError: If `api_key` is not provided (empty string).
        """

        if model is None:
            brick_config = get_brick_config(self.__class__)
            app_configured_model = get_brick_configured_model(brick_config.get("id") if brick_config else None)
            if app_configured_model:
                logger.debug(f"Using model: '{app_configured_model}'.")
                model = app_configured_model
            else:
                model = brick_config.get("model", None)
                logger.debug(f"Using default model: '{model}'.")

        super().__init__(
            model=model,
            api_key=api_key,
            system_prompt=system_prompt,
            temperature=temperature,
            max_tokens=max_tokens,
            timeout=timeout,
            tools=tools,
            **kwargs,
        )
        super().with_memory(0)  # Initialize without memory enabled (0 means no history)

    def get_client(self) -> BaseChatModel:
        """Returns the underlying LangChain model instance.

        This allows for advanced users to access the full capabilities of the model
        directly, such as calling `generate()` or `stream()` with custom message formats.

        Returns:
            BaseChatModel: The LangChain chat model instance used internally.
        """
        return self._model

    def chat(self, message: str, images: List[str | bytes] = None) -> str:
        """Sends a message to the AI and blocks until the complete response is received.

        This method automatically manages conversation history if memory is enabled.

        Args:
            message (str): The input text prompt from the user.
            images (List[str | bytes]): Optional list of image file paths or raw bytes to include in the prompt.

        Returns:
            str: The complete text response generated by the AI.

        Raises:
            RuntimeError: If the internal chain is not initialized or if the API request fails.
        """
        try:
            return super()._chat_invoke(message=message, images=images)
        except (openai.BadRequestError, openai.APIError) as e:
            self._handle_api_error(e)

    def chat_stream(self, message: str, images: List[str | bytes] = None) -> Iterator[str]:
        """Sends a message to the AI and yields response tokens as they are generated.

        This allows for processing or displaying the response in real-time (streaming).
        The generation can be interrupted by calling `stop_stream()`.

        Args:
            message (str): The input text prompt from the user.
            images (List[str | bytes]): Optional list of image file paths or raw bytes to include in the prompt.

        Yields:
            str: Chunks of text (tokens) from the AI response.

        Raises:
            RuntimeError: If the internal chain is not initialized or if the API request fails.
            AlreadyGenerating: If a streaming session is already active.
        """
        try:
            return super()._chat_stream_invoke(message=message, images=images)
        except (openai.BadRequestError, openai.APIError) as e:
            self._handle_api_error(e)

    def stop_stream(self) -> None:
        """Signals the active streaming generation to stop.

        This sets an internal flag that causes the `chat_stream` iterator to break
        early. It has no effect if no stream is currently running.
        """
        super().stop_stream()

    def clear_memory(self) -> None:
        """Clears the conversational memory history.

        Resets the stored context. This is useful for starting a new conversation
        topic without previous context interfering. Only applies if memory is enabled.
        """
        super().clear_memory()

    def with_memory(self, max_messages: int = 0) -> "VisionLanguageModel":
        """Enables conversational memory for this instance.

        Configures the Brick to retain a window of previous messages, allowing the
        AI to maintain context across multiple interactions.

        Args:
            max_messages (int): The maximum number of messages (user + AI) to keep
                in history. Older messages are discarded. Set to 0 to disable memory.
                Defaults to 0.

        Returns:
            VisionLanguageModel: The current instance, allowing for method chaining.
        """
        return super().with_memory(max_messages=max_messages)
