id: arduino:asr
name: Automatic Speech Recognition (ASR)
description: Automatic Speech Recognition brick for offline speech-to-text processing
category: audio
requires_model: true
requires_services: ["arduino:genie_audio"]
ai_frameworks_compatibility:
  - qnn
model: whisper-small
supported_boards: ["ventunoq"]
model_configuration_variables:
  - VAD_LEN_HANGOVER
variables:
- name: VAD_LEN_HANGOVER
  description: Length of hangover for Voice Activity Detection (in number of frames of 10ms duration)
  hidden: true
  default_value: 70