services:
  ollama-models-runner:
    image: ${DOCKER_REGISTRY_BASE:-ghcr.io/arduino/}app-bricks/ollama-models-runner:add-csi-cameras-support
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
    working_dir: /models
    ports:
      - ${BIND_ADDRESS:-127.0.0.1}:11434:11434
    mem_limit: 10g
    oom_kill_disable: false
    shm_size: 2g
    volumes:
      - ${APPLAB_DOWNLOADED_OLLAMA_MODELS:-${HOME}/ArduinoAppsSharedData/ollama/}:/models/
